all:
	g++ -o 53_HW_Q1 53_HW_Q1.c
	g++ -o 53_HW_Q2 53_HW_Q2.c
	g++ -o 53_HW_Q4_TCP_server 53_HW_Q4_TCP_server.cpp
	g++ -o 53_HW_Q4_TCP_client 53_HW_Q4_TCP_client.cpp
	g++ -o 53_HW_Q4_UDP_server 53_HW_Q4_UDP_server.cpp
	g++ -o 53_HW_Q4_UDP_client 53_HW_Q4_UDP_client.cpp
	g++ -o summ summ.c
